export const Primary = "#000000"
export const Secondary = "#FF4040"
export const White = "#FFFFFF"
export const DarkGray = "#0000002E"
export const LightGray = "#DCDCDC"
export const ScreenBackGround = "#EEEEEE"
export const Accept = "#86AA0C"
